---
name: Build and Publish Docker Workflow
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
        default: ""
      WORKDIR:
        required: false
        type: string
        default: ./
    secrets:
      IMAGE_TAG:
        required: true
      IMAGE_VERSION:
        required: true
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      GKE_SA_KEY:
        required: true
      PROJECT_ID:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: ./.github/actions/setup-gcloud
      with:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

    - name: Build docker image
      working-directory: ${{ inputs.WORKDIR }}
      run: |-
        docker build \
        -t ${{ secrets.IMAGE_TAG }}:latest \
        -t ${{ secrets.IMAGE_TAG }}:${{ secrets.IMAGE_VERSION }} \
        --build-arg NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }} \
        --build-arg NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }} \
        --build-arg PROJECT_ID=${{ secrets.PROJECT_ID }} \
        "."
      shell: bash

    - name: Push docker image
      run: |-
        docker push ${{ secrets.IMAGE_TAG }}:latest
        docker push ${{ secrets.IMAGE_TAG }}:${{ secrets.IMAGE_VERSION }}
      shell: bash
